### ISSUE TITLE
Question about second-order gradients for GRU

### ISSUE THREAD

**Issue by Nithin-Holla** [facebookresearch/higher#27] opened 2020-01-22 11:17 UTC
Hi, I was trying to use the package for obtaining second-order gradients through the optimization process of a model with GRU units each followed by a linear layer. However, when I check `torch.autograd.grad(loss, learner_fmodel.parameters(time=0))` I get the error `RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.`. With `allow_unused=True`, I see that the gradients with respect to the GRU parameters are `None` whereas the gradient with respect to the linear layer has values. I was wondering if this is indeed supported for GRU?

**Comment by egrefen** [comment] 2020-01-22 16:24
Can you please post a short self-contained code snippet which replicates the issue, and ensure you  are on the latest version of higher (`cd higher; pip -U .`)? GRUs should be supported.

**Comment by Nithin-Holla** [comment] 2020-01-22 22:00
@egrefen Yes, I am on the latest version of higher. Here is a sample code:

`import copy

import higher
from torch import nn, optim
import torch
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence


class Base(nn.Module):
    def __init__(self, hidden=10):
        super(Base, self).__init__()
        self.hidden = hidden
        self.gru = nn.GRU(input_size=50,
                          hidden_size=self.hidden,
                          num_layers=1,
                          batch_first=True,
                          bidirectional=True
                          )
        self.linear = nn.Linear(2 * self.hidden, 10)
        self.tanh = nn.Tanh()

    def forward(self, input, input_len):
        packed = pack_padded_sequence(input, input_len, batch_first=True, enforce_sorted=False)
        hidden, _ = self.gru(packed)
        hidden, _ = pad_packed_sequence(hidden, batch_first=True)
        hidden = self.tanh(hidden)
        d = self.tanh(self.linear(hidden))
        return d


class MetaModel(nn.Module):
    def __init__(self):
        super(MetaModel, self).__init__()
        self.learner = Base()
        self.loss = nn.CrossEntropyLoss()
        self.lr = 0.1

    def forward(self, support_x, support_y, support_len, query_x, query_y, query_len):
        learner = copy.deepcopy(self.learner)
        params = [p for p in learner.parameters() if p.requires_grad]
        optimizer = optim.SGD(params, lr=self.lr)
        with higher.innerloop_ctx(learner, optimizer) as (fmodel, diffopt):
            output = fmodel(support_x, support_len)
            loss = self.loss(output.view(-1, 10), support_y.view(-1))
            diffopt.step(loss)
            output = fmodel(query_x, query_len)
            loss = self.loss(output.view(-1, 10), query_y.view(-1))
            grads = torch.autograd.grad(loss, fmodel.parameters(time=0), allow_unused=True)
        return grads


if __name__ == '__main__':
    support_x = torch.randn(size=(5, 10, 50))
    support_y = torch.randint(0, 10, size=(5, 10))
    support_len = torch.ones(5) * 10
    query_x = torch.randn(size=(5, 10, 50))
    query_y = torch.randint(0, 10, size=(5, 10))
    query_len = torch.ones(5) * 10

    model = MetaModel()
    grads = model(support_x, support_y, support_len, query_x, query_y, query_len)
    for id, grad in enumerate(grads):
        print('Gradient of param {}: {}'.format(id, grad))
`

**Comment by berlino** [comment] 2020-02-10 22:00
I got a similar issue when I was trying to use the package for lstm. The gradient with respect the parameters of the lstms are always none.

**Comment by Nithin-Holla** [comment] 2020-02-11 14:37
@berlino Thanks! The above code segment seems to work with PyTorch 1.3

**Comment by egrefen** [comment] 2020-02-11 14:48
@berlino @Nithin-Holla Thanks for flagging this. I had not noted any problems here, but I will look to reproduce this on pytorch 1.4 and loop in someone from the pytorch team if necessary.

**Comment by egrefen** [comment] 2020-02-13 13:07
Just to update you, I can also reproduce this error. Eyeballing the current pytorch rnn code, I'm not sure why this is happening, so will need to loop in someone from the pytorch team.

I note that the unit tests for RNNs in higher is incomplete and wouldn't catch this, so I will fix that first, and then try to get this progressed.

This is a blocking issue for my own research so will try to get this sorted ASAP.

**Comment by egrefen** [comment] 2020-02-26 10:14
@berlino @Nithin-Holla I've added further unit tests in #36, and can confirm there is nothing wrong with `torch.nn.{GRU,LSTM,RNN}`. The issue seems to be with the used of `pack_padded_sequence` and `pad_packed_sequence`. I will look into this further, but if you need to make progress with your projects I suggest not using these functions for the time being while I investigate.

**Comment by egrefen** [comment] 2020-02-26 10:28
As the bug has nothing to do with the RNN implementations, but rather with utility functions, I've started a separate issue with an adaption of your minimal repro example. Please follow #38 if you want to track a resolution or contribute to a discussion. Closing this issue to avoid confusion.

**Comment by egrefen** [comment] 2020-02-26 11:29
Looks like the issue is not due to packing. The following minimal repro based on @Nithin-Holla's example still shows null grads:
```python
import higher
import torch

class Base(torch.nn.Module):
    def __init__(self, hidden, classes):
        super(Base, self).__init__()
        self.hidden = hidden
        self.classes = classes
        self.gru = torch.nn.RNN(input_size=self.hidden,
                                hidden_size=self.hidden)
        self.linear = torch.nn.Linear(self.hidden, self.classes)

    def forward(self, inputs):
        h, _ = self.gru(inputs)
        d = self.linear(h)
        return d

batch_size = 2
seq_len = 3
num_classes = 4
num_feats = 5

learner = Base(num_feats, num_classes)
loss_fn = torch.nn.CrossEntropyLoss()
lr = 0.1

xs = torch.randn(size=(seq_len, batch_size, num_feats))
y = torch.randint(num_classes, size=(seq_len, batch_size))
test_xs = torch.randn(size=(seq_len, batch_size, num_feats))
test_y = torch.randint(num_classes, size=(seq_len, batch_size))

optimizer = torch.optim.SGD(learner.parameters(), lr=lr)
with higher.innerloop_ctx(learner, optimizer) as (fmodel, diffopt):
    output = fmodel(xs)
    loss = loss_fn(
        output.view(-1, num_classes), 
        y.view(-1)
        )
    diffopt.step(loss)
    test_output = fmodel(test_xs)
    loss = loss_fn(
        test_output.view(-1, num_classes), 
        test_y.view(-1)
        )

    grads = torch.autograd.grad(loss, fmodel.parameters(time=0), allow_unused=True)
    
grad_is_none = [g is None for g in grads]

if any(grad_is_none):
    for id, grad in enumerate(grads):
        if grad is None:
            print('Gradient of param {}: {}'.format(id, grad))
        else:
            print('Gradient of param {}: {}'.format(id, grad.shape))
else:
    print("All good!")
```
Re-opening this issue to deal with it.

**Comment by egrefen** [comment] 2020-02-26 12:18
Further narrowing it down, a simpler example:
```python
import higher
import torch

class Base(torch.nn.Module):
    def __init__(self, hidden, classes):
        super(Base, self).__init__()
        self.hidden = hidden
        self.classes = classes
        self.rnn = torch.nn.RNN(input_size=self.hidden,
                                hidden_size=self.hidden)
        self.linear = torch.nn.Linear(self.hidden, self.classes)

    def forward(self, inputs):
        h, _ = self.rnn(inputs)
        d = self.linear(h)
        return d
    
batch_size = 2
seq_len = 3
num_classes = 4
num_feats = 5
lr = 0.1

model = Base(num_feats, num_classes)
loss_fn = torch.nn.CrossEntropyLoss()

xs = torch.randn(size=(seq_len, batch_size, num_feats))
y = torch.randint(num_classes, size=(seq_len, batch_size))

fmodel = higher.monkeypatch(model)
output = fmodel(xs)
loss = loss_fn(
    output.view(-1, num_classes), 
    y.view(-1)
    )
print(torch.autograd.grad(loss, fmodel.parameters(), allow_unused=True))
```

No `None` gradients for the RNN component in torch v1.3.x, but all `None` for v1.4.0.

**Comment by egrefen** [comment] 2020-02-26 16:39
I've identified where the problem is. Working on a fix...

**Comment by egrefen** [comment] 2020-02-26 17:45
@berlino @Nithin-Holla Can you please check out if the changes introduced in #39 fix your problems? It should solve the minimal working examples in this thread (those I've tried, at least). 

You can just checkout the `rnn_fix` branch (and `pip install -U .` from the root dir if you have `higher` installed).

I'll leave the PR open until Friday and merge then (midday UK time) if I haven't heard back.

**Comment by Nithin-Holla** [comment] 2020-02-26 23:24
@egrefen It works now. Thanks for fixing this!

**Closed** 2020-02-27 11:46 UTC

**Comment by berlino** [comment] 2020-02-27 11:54
@egrefen It works for me as well. Thanks for the effort!
