### ISSUE TITLE
Registering optimizer does not work

### ISSUE THREAD

**Issue by renesax14** [facebookresearch/higher#35] opened 2020-02-22 00:15 UTC
I tried registering my own optimizer. I gave a minimal sample code:

```
import torch
import torch.nn as nn
from torch.optim.optimizer import Optimizer

import higher
from higher.optim import DifferentiableOptimizer

from collections import OrderedDict

class MySGD(Optimizer):

    def __init__(self, params):
        defaults = {}
        super().__init__(params,defaults)

    def _update(self, grouped_grads, **kwargs):
        pass

class MyDiffOpt(DifferentiableOptimizer):

    def _update(self, grouped_grads, **kwargs):
        pass

# initialize model and (original) optimizer
model = nn.Sequential(OrderedDict([('fc', nn.Linear(1,1)),('sigmoid', nn.Sigmoid())]))
other = MySGD(model.parameters())
# get differentiable optimizer
inner_opt = MyDiffOpt(other, model.parameters())
higher.register_optim(MySGD, MyDiffOpt)
with higher.innerloop_ctx(model, inner_opt) as (fmodel, diffopt):
    print(f'diffopt = {diffopt}')

```

error msg:

```
Exception has occurred: ValueError
Optimizer type <class '__main__.MyDiffOpt'> not supported by higher yet.
```

related to issue: https://github.com/facebookresearch/higher/issues/34

**Comment by egrefen** [comment] 2020-02-22 00:52
This is working as intended. When you call `higher.register_optim(MySGD, MyDiffOpt)` you are telling `higher` "hey, just FYI, I wrote `MyDiffOpt` as a differentiable implementation of `MySGD`" (as a side note, the library is not responsible for checking that this is actually the case). This then allows you to use high level functions like `higher.innerloop_ctx` over instances of `MySGD` which will be mapped to statefully equivalent versions of their differentiable counterpart, as if they had been supported by `higher` natively. Neat, huh?

What's going wrong in your code is that `inner_opt` is an instance of `MyDiffOpt` (a `DifferentiableOptimizer` subclass) when in fact this function expects a `Optimizer` subclass instance.

I'll give you feedback on how to do things as I think you want to do them in #34 when I have some time next week.

In the meantime, closing this issue as there's no bug.

**Closed by egrefen** 2020-02-22 00:52 UTC

**Comment by renesax14** [comment] 2020-02-22 00:59
> This is working as intended. When you call `higher.register_optim(MySGD, MyDiffOpt)` you are telling `higher` "hey, just FYI, I wrote `MyDiffOpt` as a differentiable implementation of `MySGD`" (as a side note, the library is not responsible for checking that this is actually the case). This then allows you to use high level functions like `higher.innerloop_ctx` over instances of `MySGD` which will be mapped to statefully equivalent versions of their differentiable counterpart, as if they had been supported by `higher` natively. Neat, huh?
> 
> What's going wrong in your code is that `inner_opt` is an instance of `MyDiffOpt` (a `DifferentiableOptimizer` subclass) when in fact this function expects a `Optimizer` subclass instance.
> 
> I'll give you feedback on how to do things as I think you want to do them in #34 when I have some time next week.
> 
> In the meantime, closing this issue as there's no bug.

ooops your right!
